{{- if .Values.cainjector.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cainjector.fullname" . }}
  namespace: {{ include "cert-manager.namespace" . }}
  labels:
    app: {{ include "cainjector.name" . }}
    app.kubernetes.io/name: {{ include "cainjector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "cainjector"
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cainjector.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "cainjector"

  {{- if and .Values.cainjector.podDisruptionBudget.minAvailable (not (hasKey .Values.cainjector.podDisruptionBudget "maxUnavailable")) }}
  minAvailable: {{ .Values.cainjector.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if hasKey .Values.cainjector.podDisruptionBudget "maxUnavailable" }}
  maxUnavailable: {{ .Values.cainjector.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
