name: Run tests
on:
  push:

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Run tets
        run: make test RELEASE_VERSION=0.0.0