# This Kustomization is used to adapt the upstream Pod security policy for use
# specifically in the cert-manager namespace.
# * Changes ClusterPolicy resources to namespaced Policy.
# * Changes the failure action of the restrict_automount_sa_token policy from Audit to Enforce.
#
# Use as follows:
#  kustomize build . > policy.yaml
resources:
  - https://github.com/kyverno/policies/pod-security/enforce
  - https://raw.githubusercontent.com/kyverno/policies/main/other/res/restrict-automount-sa-token/restrict-automount-sa-token.yaml
  - https://github.com/kyverno/policies/raw/main//best-practices/require-ro-rootfs/require-ro-rootfs.yaml
patches:
  - patch: |-
      - op: replace
        path: /kind
        value: Policy
      - op: add
        path: /metadata/namespace
        value: cert-manager
      - op: replace
        path: /spec/validationFailureAction
        value: Enforce
    target:
      kind: ClusterPolicy
